name: Deploy to Amazon ECS CI/CD

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: waiting-repo
  ECS_SERVICE: waiting-service
  ECS_CLUSTER: allclear_cluster
  CONTAINER_NAME: waiting-container

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create application.yml
        if: contains(github.ref, 'main')
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml
        shell: bash

      - name: Add CA certificate
        run: |
          echo "${{ secrets.CA_CERT }}" > ca-cert.pem
          echo "${{ secrets.PRIVATE_KEY }}" > private-key.pem
          echo "${{ secrets.CA_CHAIN }}" > ca-chain.pem
          openssl pkcs12 -export \
            -in ca-cert.pem \
            -inkey private-key.pem \
            -out keystore.p12 \
            -name Hanium \
            -CAfile ca-chain.pem \
            -caname root \
            -passin pass:${{ secrets.KEYSTORE_PASSWORD }} \
            -passout pass:${{ secrets.KEYSTORE_PASSWORD }}
        shell: bash

      - name: Generate keystore
        run: |
          keytool -importkeystore \
            -srckeystore keystore.p12 \
            -srcstoretype PKCS12 \
            -srcstorepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -destkeystore hanium.jks \
            -deststoretype JKS \
            -deststorepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -destkeypass ${{ secrets.KEYSTORE_PASSWORD }}
        shell: bash

      - name: Verify keystore.p12 exists in root
        run: |
          if [ -f "keystore.p12" ]; then
            echo "keystore.p12 was successfully created in the root directory."
          else
            echo "keystore.p12 not found in the root directory."
            exit 1
          fi
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build -x test
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Write ECS task definition to file
        run: echo "${{ secrets.ECS_TASK_DEFINITION_JSON }}" > waiting-task.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: waiting-task.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
